version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gondor
  app:
    image: hereisnaman/gondor
    depends_on:
      - postgres
    ports:
    - "3000:3000"
    env_file:
      - .env
